# Generated by Django 3.2.5 on 2022-05-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0003_auto_20220518_1100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jejuolle',
            table='jeju_olle',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shop',
        ),
    ]
