# Generated by Django 3.2.5 on 2022-05-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_alter_armyshop_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armyshop',
            table='army_shop',
        ),
    ]
